"""empty message

Revision ID: 0ac4ebfe42f0
Revises: 01e06ee938c7
Create Date: 2025-03-20 12:09:17.964763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac4ebfe42f0'
down_revision = '01e06ee938c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('port', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mining_node')
    # ### end Alembic commands ###
